name: Build

on:
  push:
    branches: [ main ]
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ main ]

permissions:
      id-token: write
      contents: read

env:
  node-version: 14.x

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ env.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ env.node-version }}
    - run: npm ci
    - run: npm run build
  
    - name: Trigger next workflow
      if: success()
      uses: peter-evans/repository-dispatch@v1
      with:
        token: ${{ secrets.REPO_NHL_DATA_GETTER_PAT }}
        repository: ${{ github.repository }}
        event-type: trigger-test-workflow
        client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'